=== champix56/2025-09-16-lsx/cvsgen.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD generated by XMLSpy v2023 rel. 2 (x64) (http://www.altova.com) -->
<!ELEMENT cv (ident, formations, experiences)>
<!ATTLIST cv
	id ID #REQUIRED
>
<!ELEMENT cvs (cv+, best-cv?,best-of-cv?)>
<!ELEMENT fin (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT debut (#PCDATA)>
<!ELEMENT ident (nom, prenom+, datenaiss, langues, permis)>
<!ATTLIST ident
	identid ID #IMPLIED>
<!ELEMENT langue EMPTY>
<!ATTLIST langue
	langName CDATA #REQUIRED
	matern CDATA #REQUIRED
>
<!ELEMENT permis (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT diplome (intitule)>
<!ATTLIST diplome
	obtenu CDATA #REQUIRED
>
<!ELEMENT langues (langue+)>
<!ELEMENT diplomes (diplome+)>
<!ELEMENT intitule (#PCDATA)>
<!ATTLIST intitule
	opt CDATA #IMPLIED
>
<!ELEMENT datenaiss (#PCDATA)>
<!ELEMENT formation (debut, fin, intitule, diplomes)>
<!ELEMENT experience (debut, fin?, intitule)>
<!ELEMENT formations (formation+)>
<!ELEMENT experiences (experience+)>
<!ELEMENT best-cv EMPTY>
<!ATTLIST best-cv 
	id IDREF #REQUIRED>
	<!ELEMENT best-of-cv EMPTY>
<!ATTLIST best-of-cv 
	ids IDREFS #REQUIRED>

=== champix56/2025-09-16-lsx/cv.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet href="css/cvs.css" type="text/css"?>
<!DOCTYPE cvs SYSTEM "cvsgen.dtd">
<cvs>
	<cv id="C239">
		<ident>
			<nom>DESORBAIX</nom>
			<prenom>Alexandre</prenom>
			<prenom>Dominique</prenom>
			<prenom>Joël</prenom>
			<datenaiss>1984-08-03</datenaiss>
			<langues>
				<langue langName="FR" matern="true"/>
				<langue langName="EN" matern="false"/>
			</langues>
			<permis>AB</permis>
		</ident>
		<formations>
			<formation>
				<debut>2000</debut>
				<fin>2008</fin>
				<intitule>Ecole privée EVRY(91)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule opt="dev">BTS IG</intitule>
					</diplome>
					<diplome obtenu="true">
						<intitule>Licence assistant Chef de projet</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Master Chef de projet</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<debut>2009</debut>
				<fin>2010</fin>
				<intitule>Fac de versailles (78)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule>Doctorat Informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<debut>2009</debut>
				<intitule>Formateur Orsys</intitule>
			</experience>
			<experience>
				<debut>2009</debut>
				<fin>2012</fin>
				<intitule>Consultant pour Ste privée</intitule>
			</experience>
		</experiences>
	</cv>
	<cv id="C245">
		<ident>
			<nom>DESORBAIX</nom>
			<prenom>Alexandre</prenom>
			<prenom>Dominique</prenom>
			<prenom>Joël</prenom>
			<datenaiss>1984-08-03</datenaiss>
			<langues>
				<langue langName="FR" matern="true"/>
				<langue langName="EN" matern="false"/>
			</langues>
			<permis>AB</permis>
		</ident>
		<formations>
			<formation>
				<debut>2000</debut>
				<fin>2008</fin>
				<intitule>Ecole privée EVRY(91)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule opt="dev">BTS IG</intitule>
					</diplome>
					<diplome obtenu="true">
						<intitule>Licence assistant Chef de projet</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Master Chef de projet</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<debut>2009</debut>
				<fin>2010</fin>
				<intitule>Fac de versailles (78)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule>Doctorat Informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<debut>2009</debut>
				<intitule>Formateur Orsys</intitule>
			</experience>
			<experience>
				<debut>2009</debut>
				<fin>2012</fin>
				<intitule>Consultant pour Ste privée</intitule>
			</experience>
		</experiences>
	</cv>
	<cv id="C234">
		<ident>
			<nom>DESORBAIX</nom>
			<prenom>Alexandre</prenom>
			<prenom>Dominique</prenom>
			<prenom>Joël</prenom>
			<datenaiss>1984-08-03</datenaiss>
			<langues>
				<langue langName="FR" matern="true"/>
				<langue langName="EN" matern="false"/>
			</langues>
			<permis>AB</permis>
		</ident>
		<formations>
			<formation>
				<debut>2000</debut>
				<fin>2008</fin>
				<intitule>Ecole privée EVRY(91)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule opt="dev">BTS IG</intitule>
					</diplome>
					<diplome obtenu="true">
						<intitule>Licence assistant Chef de projet</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Master Chef de projet</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<debut>2009</debut>
				<fin>2010</fin>
				<intitule>Fac de versailles (78)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule>Doctorat Informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<debut>2009</debut>
				<intitule>Formateur Orsys</intitule>
			</experience>
			<experience>
				<debut>2009</debut>
				<fin>2012</fin>
				<intitule>Consultant pour Ste privée</intitule>
			</experience>
		</experiences>
	</cv>
	<cv id="C235">
		<ident>
			<nom>DESORBAIX</nom>
			<prenom>Alexandre</prenom>
			<prenom>Dominique</prenom>
			<prenom>Joël</prenom>
			<datenaiss>1984-08-03</datenaiss>
			<langues>
				<langue langName="FR" matern="true"/>
				<langue langName="EN" matern="false"/>
			</langues>
			<permis>AB</permis>
		</ident>
		<formations>
			<formation>
				<debut>2000</debut>
				<fin>2008</fin>
				<intitule>Ecole privée EVRY(91)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule opt="dev">BTS IG</intitule>
					</diplome>
					<diplome obtenu="true">
						<intitule>Licence assistant Chef de projet</intitule>
					</diplome>
					<diplome obtenu="false">
						<intitule>Master Chef de projet</intitule>
					</diplome>
				</diplomes>
			</formation>
			<formation>
				<debut>2009</debut>
				<fin>2010</fin>
				<intitule>Fac de versailles (78)</intitule>
				<diplomes>
					<diplome obtenu="true">
						<intitule>Doctorat Informatique</intitule>
					</diplome>
				</diplomes>
			</formation>
		</formations>
		<experiences>
			<experience>
				<debut>2009</debut>
				<intitule>Formateur Orsys</intitule>
			</experience>
			<experience>
				<debut>2009</debut>
				<fin>2012</fin>
				<intitule>Consultant pour Ste privée</intitule>
			</experience>
		</experiences>
	</cv>
	<best-cv id="C234"/>
	<best-of-cv ids="C234 C239"/>
</cvs>
